---
title: "Plots for /ideas"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Impact vs Ease

```{r}
log_example <- function(x){ 
  val <- log(10*x) + 5.39483
  val[val < 0] <- 0
  val
}

tibble() %>%
  ggplot(aes()) + 
  # stat_function(fun = function(x) x) +
  stat_function(fun = function(x) 0.001 * x^4) +
  # stat_function(fun =  log_example) +
  expand_limits(x = c(0, 10), y = c(0,10)) +
  coord_cartesian() + 
  scale_y_continuous(breaks = scales::pretty_breaks()) + 
  scale_x_continuous(breaks = scales::pretty_breaks()) +
  labs(
    # title = "Impact & Effort: Linear Relationship",
    title = "Impact & Effort: \nExponential Relationship",
    # title = "Impact & Effort: Pareto Principle",
       y = "Impact",
       x = "Effort")

```


# Speed vs Velocity

```{r}
speedy <- tribble(
 ~x_start, ~y_start, ~x_end, ~y_end,
 0, 0, 1, 4,
 0, 0, -4, 2,
 0, 0, -5, -3,
 0, 0, 3, -4,
 0, 0, -2, 3
) 

speedy_summary <- tribble(
  ~x_start, ~y_start, ~x_end, ~y_end,
  0, 0, 1, 4,
  1, 4, -3, 6,
  -3, 6, -8, 3,
  -8, 3, -5, -1,
  -5, -1, -7, 2
) %>% mutate(approach = "Focus on speed")
  

velocitous <- tribble(
  ~x_start, ~y_start, ~x_end, ~y_end,
  0, 0, 2, 2,
  0, 0, 0, 4,
  0, 0, 2, 1,
  0, 0, 3, -1,
  0, 0, 1, 3
)

velocitous_summary <- tribble(
  ~x_start, ~y_start, ~x_end, ~y_end,
  0, 0, 2, 2,
  2, 2, 0, 6,
  0, 6, 4, 7,
  4, 7, 7, 6,
  7, 6, 8, 9
) %>% mutate(approach = "Focus on velocity")

summary_df <- bind_rows(speedy_summary, velocitous_summary)

df <- bind_rows(
  speedy %>%
    mutate(approach = "Focus on speed"),
  velocitous %>%
    mutate(approach = "Focus on velocity")
)

net_df <- df %>%
  group_by(approach) %>%
  summarise(x_end = sum(x_end),
            y_end = sum(y_end))


df %>%
  ggplot(aes(x_start, y_start)) + 
  # geom_point(aes(0,0, color = 'Start'), size = 3) + 
  geom_point(aes(10,10, color = 'Goal'), size = 3) + 
  geom_segment(aes(x_start, y_start, xend = x_end, yend = y_end), arrow = arrow(length = unit(.2, "cm"))) + 
  # geom_segment(aes(x_start, y_start, xend = x_end, yend = y_end), color = "red", arrow = arrow(length = unit(.2, "cm")), data = summary_df) +
  geom_segment(aes(0, 0, xend = x_end, yend = y_end), color = "red", arrow = arrow(length = unit(.2, "cm")), data = net_df) +
  geom_label(aes(x_end, y_end, label = "net progress"), nudge_y = -1.5, data = net_df) +
  expand_limits(x = c(-10, 10), y = c(-10, 10)) +
  facet_wrap(~approach) + 
  coord_fixed() +
  labs(color = "",
       x = "",
       y = "")
```

